TopTalk/TopTalkSite/TopTalkSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^simple_registration/', include('simple_registration.urls')),
    url(r'^admin/', admin.site.urls),
]

TopTalk/TopTalkSite/simple_registration/urls.py
from django.conf.urls import url 
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index$', views.index, name='index'),
]

TopTalk/TopTalkSite/simple_registration/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

# Create your models here.
@python_2_unicode_compatible
class Info(models.Model):
    """Basic information of applicants"""
    # 姓名
    name = models.CharField(verbose_name='姓名', 
        max_length=128, blank=True)
    # 工作单位
    organization = models.CharField(verbose_name='工作单位', 
        max_length=128, blank=True)
    # 手机号
    phone_number = models.CharField(verbose_name='手机号', 
        max_length=128, blank=True)
    # 邮箱
    email = models.CharField(verbose_name='邮箱', 
        max_length=128, blank=True)
    # 人员类别
    BACHELOR, MASTER, DOCTOR, OTHER = 1, 2, 3, 0
    CATEGORY_CHOICES = (
            (BACHELOR, '本科'),
            (MASTER, '硕士'),
            (DOCTOR, '博士'),
            (OTHER, '其他'),
        )
    category = models.IntegerField(verbose_name='人员类别', 
        choices=CATEGORY_CHOICES, default=OTHER)
    # 审核结果
    UNCHECKED, PASSED, FAILED = 0, 1, 2
    CHECK_STATUS_CHOICES = (
            (UNCHECKED, '未审核'),
            (PASSED, '通过'),
            (FAILED, '未通过'),
        )
    check_status = models.IntegerField(verbose_name='审核结果',
        choices=CHECK_STATUS_CHOICES, default=UNCHECKED)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '报名信息'
        verbose_name_plural = '所有报名信息'
        

TopTalk/TopTalkSite/simple_registration/forms.py
from django.forms import ModelForm
from .models import Info


class InfoForm(ModelForm):
    class Meta:
        model = Info
        fields = ['name', 'organization', 'phone_number',
                  'email', 'category',
        ]

TopTalk/TopTalkSite/simple_registration/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from .models import Info
from .forms import InfoForm

# Create your views here.
def index(request):
    if request.method == 'GET':
        form = InfoForm()
        context = {'form': form}
        # weihe edited: wrong template path. 04/29
        return render(request, 'simple_registration/index.html', context)
    else:
        form = InfoForm(request.POST)
        if form.is_valid():
            info = form.save()
            return HttpResponse('成功提交表单')
        else:
            return HttpResponse('表单错误！')

TopTalk/TopTalkSite/templates/simple_registration/index.html
{% load static %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!--<link rel="stylesheet" href="{% static 'simple_registration/css/simplegrid.css' %}" />-->
  <!--<link rel="stylesheet" href="{% static 'simple_registration/css/form.css' %}" />-->
  <link rel="stylesheet" href="{% static 'simple_registration/css/formBetter.css' %}" />

  <title></title>
</head>

<body>
  <div class="grid grid-pad" id="form-wrapper">
    <form method="post" action="index">
      {% csrf_token %}

      <div class="col-6-12 input-field">
        <input type="text" name="name" placeholder="姓名" id="id_name" maxlength="128" required/>
      </div>

      <div class="col-8-12 input-field">
        <input type="text" name="organization" placeholder="工作单位" id="id_organization" maxlength="128" required/>
      </div>

      <div class="col-8-12 input-field">
        <input type="text" name="phone_number" placeholder="手机号" id="id_phone_number" maxlength="128" required/>
      </div>

      <div class="col-8-12 input-field">
        <input type="email" name="email" placeholder="邮箱" id="id_email" maxlength="128" required/>
      </div>

      <div class="col-8-12 input-field">
        <select name="category" placeholder="人员类别" id="id_category">
          <option value="1">本科</option>

          <option value="2">硕士</option>

          <option value="3">博士</option>

          <option value="0" selected>其他</option>

        </select>
      </div>


      <div class="col-12-12 input-button">
        <input type="submit" value="OK" />
        <div class="ease"></div>
      </div>
    </form>
  </div>
</body>

</html>

TopTalk/TopTalkSite/templates/simple_registration/index_bak.html
{% load static %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static 'css/simplegrid.css' %}" />
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
  <!--<link rel="stylesheet" href="{% static 'css/formBetter.css' %}" />-->

  <title></title>
</head>

<body>
  <div class="grid grid-pad" id="form-wrapper">
    <form method="post" action="index">
      {% csrf_token %}
      <div class="col-4-12 input-label">
        <label for="{{ form.name.id_for_label }}">姓名:</label>
      </div>
      <div class="col-6-12 input-field">
        {{ form.name }}
      </div>
      <div class="col-4-12 input-label">
        <label for="{{ form.organization.id_for_label }}">工作单位:</label>
      </div>
      <div class="col-8-12 input-field">
        {{ form.organization }}
      </div>
      <div class="col-4-12 input-label">
        <label for="{{ form.phone_number.id_for_label }}">手机号:</label>
      </div>
      <div class="col-8-12 input-field">
        {{ form.phone_number }}
      </div>
      <div class="col-4-12 input-label">
        <label for="{{ form.email.id_for_label }}">邮箱:</label>
      </div>
      <div class="col-8-12 input-field">
        {{ form.email }}
      </div>
      <div class="col-4-12 input-label">
        <label for="{{ form.category.id_for_label }}">人员类别:</label>
      </div>
      <div class="col-8-12 input-field">
        {{ form.category }}
      </div>
      <div class="col-12-12 input-button">
        <input type="submit" value="OK" />
      </div>
    </form>
  </div>
</body>

</html>